### ISSUE TITLE
Invoke i18n for error handler

### ISSUE THREAD

**Issue by JoeChapman** [UKHomeOffice/gro#94]
Invoke i18n for error handler as describe in https://github.com/UKHomeOffice/hof-middleware/issues/12

**Comment by joefitter** [comment]
Translate should

**Comment by joefitter** [comment]
translate function should be taken from options if provided, if not then should use req.translate (after app middleware). In this case not providing a translate function will mean it uses deepTranslate middleware

**Comment by JoeChapman** [comment]
This is done
